packages:
  - "packages/*"

catalogs:
  default:
    electron: ^37.3.1
    webdriverio: ^9.19.1
    "@wdio/cli": ^9.19.2
    "@wdio/globals": ^9.17.0
    "@wdio/local-runner": ^9.19.1
    "@wdio/mocha-framework": ^9.19.1
    "@wdio/types": ^9.19.1
    "@wdio/logger": ^9.18.0
    "@wdio/xvfb": ^9.19.1
    wdio-electron-service: ^9.0.0-next.5
  next:
    electron: latest
    webdriverio: latest
    "@wdio/cli": latest
    "@wdio/globals": latest
    "@wdio/local-runner": latest
    "@wdio/mocha-framework": latest
    "@wdio/types": latest
    "@wdio/logger": latest
    "@wdio/xvfb": latest
    wdio-electron-service: next
  minimum:
    electron: ^28.0.0
    webdriverio: ^8.43.0
    "@wdio/cli": ^8.43.0
    "@wdio/globals": ^8.43.0
    "@wdio/local-runner": ^8.43.0
    "@wdio/mocha-framework": ^8.41.0
    "@wdio/types": ^8.41.0
    "@wdio/logger": ^8.41.0
    "@wdio/xvfb": ^9.19.1
    wdio-electron-service: lts
